name: quotable_app
description: "Bismillah."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.0+4

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_card_swiper: ^6.1.0
  equatable: ^2.0.3
  path_provider: ^2.0.2
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  flutter_tts: ^3.3.3
  share_plus: ^2.1.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^8.1.1
  screenshot: ^2.1.0
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/anim/loading.json
    - assets/anim/networkeror.json
